#!/usr/bin/env python3
"""Validate a project generated by Agent Builder.

Deterministic structural and secret-safety checks. Reads the project's kind from
``.agent-builder.json`` and requires the files that kind needs. Never modifies the project.

Usage:
    python3 check.py PATH                  # exit 0 when valid, 1 with one line per issue
    python3 check.py PATH --since          # what changed in Agent Builder since this project
                                           # was seeded (reads template_version from the manifest)
    python3 check.py PATH --since 0.1.0    # ... since a specific version
    python3 check.py PATH --leaving define # may this project leave Define? exit 0 yes, 1 no,
                                           # one line per unresolved item (AB-D033, AB-D035)
"""

from __future__ import annotations

import sys

if sys.version_info < (3, 9):  # noqa: UP036 - deliberate guard for older interpreters
    sys.stderr.write(
        f"Agent Builder needs Python 3.9 or newer; this is "
        f"{sys.version_info[0]}.{sys.version_info[1]}. Install a newer Python and run this again.\n"
    )
    sys.exit(2)

import argparse  # noqa: E402
import json  # noqa: E402
import re  # noqa: E402
from dataclasses import dataclass  # noqa: E402
from pathlib import Path  # noqa: E402

_ADAPTER_FILES = {
    "codex": Path("AGENTS.md"),
    "claude": Path("CLAUDE.md"),
    "gemini": Path("GEMINI.md"),
}
_REQUIRED_FILES = (
    Path(".agent-builder.json"),
    Path(".env.example"),
    Path(".gitignore"),
    Path("README.md"),
    Path("SECURITY.md"),
    Path("governance/decisions.yaml"),
    Path("governance/operating-agreement.md"),
    Path("governance/project-state.yaml"),
    Path("planning/README.md"),
    Path("planning/open-questions.md"),
)
# Files each kind adds on top of the base set. Projects generated before kinds existed have
# no "kind" in their manifest and are treated as agents, so they keep validating unchanged.
_KIND_REQUIRED_FILES = {
    "agent": (
        Path(".dockerignore"),
        Path("contracts/examples/agent-handoff.example.json"),
        Path("contracts/schemas/agent-handoff.schema.json"),
    ),
    "skill": (
        Path("SKILL.md"),
        Path(".claude-plugin/plugin.json"),
        Path("evals/README.md"),
    ),
    "project": (),
}
_DEFAULT_KIND = "agent"
# A project's lifecycle state, independent of its phase. "active" is the default for anything
# that does not say otherwise, including projects generated before the field existed.
_PROJECT_STATUSES = ("active", "paused", "abandoned", "archived")
_STATUS_LINE = re.compile(r"^  status: ([a-z]+)$", re.MULTILINE)
_SECRET_PATTERNS = {
    "private-key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "openai-style-key": re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
    "google-api-key": re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),
    "aws-access-key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "github-token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b"),
}
_FORBIDDEN_SECRET_FILES = {".env", ".env.local", ".env.production"}
_TOKEN = re.compile(r"\{\{[A-Z0-9_]+\}\}")
_VERSION = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$")
# SemVer 2.0.0: numeric core identifiers cannot have leading zeroes; prerelease numeric
# identifiers cannot either. Build metadata permits them. https://semver.org/spec/v2.0.0.html
_SEMVER_CORE = r"(?:0|[1-9][0-9]*)"
_SEMVER_PRE = r"(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
_SEMVER_BUILD = r"[0-9A-Za-z-]+"
_SEMVER = re.compile(
    rf"{_SEMVER_CORE}\.{_SEMVER_CORE}\.{_SEMVER_CORE}"
    rf"(?:-{_SEMVER_PRE}(?:\.{_SEMVER_PRE})*)?"
    rf"(?:\+{_SEMVER_BUILD}(?:\.{_SEMVER_BUILD})*)?"
)
_SOLUTION_FIELDS = (
    "Need",
    "Search date",
    "Public sources searched",
    "User-provided codebases checked",
    "Candidate fit",
    "Utilization and maintenance",
    "Tests and security history",
    "License obligations",
    "Setup and operating burden",
    "Evidence-backed reason",
    "Author confirmation",
)
_SOLUTION_LINE = re.compile(r"^- ([^:\n]+):[ \t]*(.*)$", re.MULTILINE)
_QUALITY_FIELDS = (
    "Reused components and replaceable boundary",
    "Failure behavior and robustness",
    "Why this is the simpler, maintainable option",
)


@dataclass(frozen=True)
class ValidationIssue:
    """One actionable scaffold validation failure."""

    code: str
    message: str
    path: Path | None = None


def _load_json(path: Path, issues: list[ValidationIssue]) -> object | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        issues.append(ValidationIssue("invalid-json", str(error), path))
        return None


def _validate_contract(root: Path, issues: list[ValidationIssue]) -> None:
    schema_path = root / "contracts/schemas/agent-handoff.schema.json"
    example_path = root / "contracts/examples/agent-handoff.example.json"
    if not schema_path.is_file() or not example_path.is_file():
        return

    schema = _load_json(schema_path, issues)
    example = _load_json(example_path, issues)
    if not isinstance(schema, dict) or not isinstance(example, dict):
        return

    required = schema.get("required")
    if not isinstance(required, list) or not all(isinstance(item, str) for item in required):
        issues.append(
            ValidationIssue(
                "invalid-schema", "handoff schema must declare string required fields", schema_path
            )
        )
        return

    missing = sorted(set(required) - set(example))
    if missing:
        issues.append(
            ValidationIssue(
                "invalid-example",
                f"handoff example is missing required fields: {', '.join(missing)}",
                example_path,
            )
        )


def _scan_text_files(root: Path, issues: list[ValidationIssue]) -> None:
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        relative = path.relative_to(root)
        if relative.name in _FORBIDDEN_SECRET_FILES:
            issues.append(
                ValidationIssue("secret-file", "secret file must not be generated", relative)
            )
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            continue
        if _TOKEN.search(content):
            issues.append(ValidationIssue("template-token", "unrendered template token", relative))
        for name, pattern in _SECRET_PATTERNS.items():
            if pattern.search(content):
                issues.append(ValidationIssue("possible-secret", f"matched {name}", relative))


def _uses_solution_gate(manifest: object) -> bool:
    """Keep pre-0.3 agent and skill projects on their original contract."""
    if not isinstance(manifest, dict):
        return False
    if manifest.get("kind") == "project":
        return True  # The neutral kind first ships with this gate.
    version = manifest.get("template_version")
    match = _VERSION.fullmatch(version) if isinstance(version, str) else None
    return bool(match and tuple(map(int, match.groups())) >= (0, 3, 0))


def _solution_record_issues(root: Path, state: str, ledger: str) -> tuple[ValidationIssue, ...]:
    path = root / "planning/solution-evaluation.md"
    if not path.is_file():
        return (
            ValidationIssue("missing-solution-evaluation", "record build-or-adopt evidence", path),
        )

    fields = dict(_SOLUTION_LINE.findall(path.read_text(encoding="utf-8")))
    issues: list[ValidationIssue] = []
    for name in _SOLUTION_FIELDS:
        value = fields.get(name, "").strip()
        if not value or value.startswith("(not yet"):
            issues.append(ValidationIssue("missing-solution-evidence", f"fill in {name}", path))

    outcome = fields.get("Outcome", "").strip().lower()
    if outcome not in {"adopt", "adapt", "build"}:
        issues.append(
            ValidationIssue("missing-solution-decision", "choose adopt, adapt, or build", path)
        )
    if outcome in {"adapt", "build"}:
        for name in _QUALITY_FIELDS:
            value = fields.get(name, "").strip()
            if not value or value.startswith("(not yet"):
                issues.append(
                    ValidationIssue("missing-technical-rationale", f"fill in {name}", path)
                )
    decision_id = fields.get("Decision record", "").strip()
    if not decision_id or decision_id.startswith("(not yet"):
        issues.append(
            ValidationIssue("missing-decision-record", "name the confirmed decision record", path)
        )
    else:
        entries = list(_DECISION_ID.finditer(ledger))
        statuses = {}
        for index, entry in enumerate(entries):
            end = entries[index + 1].start() if index + 1 < len(entries) else len(ledger)
            match = _DECISION_STATUS.search(ledger, entry.end(), end)
            statuses[entry.group(1)] = match.group(1) if match else None
        if statuses.get(decision_id) != "confirmed":
            issues.append(
                ValidationIssue(
                    "unconfirmed-solution-decision",
                    f"{decision_id} must be confirmed in governance/decisions.yaml",
                    root / "governance/decisions.yaml",
                )
            )
    if outcome == "adopt":
        adopted = fields.get("Adopted solution and version", "").strip().lower()
        if not adopted or adopted == "not applicable" or adopted.startswith("(not yet"):
            issues.append(
                ValidationIssue(
                    "missing-adopted-version", "name the adopted solution and its version", path
                )
            )
        status = _STATUS_LINE.search(state)
        if not status or status.group(1) != "archived":
            issues.append(
                ValidationIssue(
                    "adoption-not-archived",
                    "archive the project after author confirmation; do not enter Build",
                    root / "governance/project-state.yaml",
                )
            )
    if outcome in {"adopt", "adapt", "build"}:
        issues.extend(_deliverable_issues(root, state, outcome))
    return tuple(issues)


def _deliverable_issues(root: Path, state: str, outcome: str) -> tuple[ValidationIssue, ...]:
    path = root / "governance/project-state.yaml"
    block = re.search(r"^deliverable:\n((?:[ \t]+.*\n)*)", state, re.MULTILINE)
    if not block:
        return (
            ValidationIssue(
                "missing-deliverable-record",
                "add a deliverable record separate from the Agent Builder template version",
                path,
            ),
        )
    fields = dict(re.findall(r"^  ([a-z_]+):[ \t]*(.*)$", block.group(1), re.MULTILINE))
    if not {"target_version", "goal"}.issubset(fields):
        return (
            ValidationIssue(
                "incomplete-deliverable-record",
                "record both target_version and goal, using null for an adoption",
                path,
            ),
        )
    version = fields.get("target_version", "").strip().strip("\"'")
    goal = fields.get("goal", "").strip().strip("\"'")
    if outcome == "adopt":
        if version not in {"", "null"} or goal not in {"", "null"}:
            return (
                ValidationIssue(
                    "adoption-has-project-release",
                    "leave the project's deliverable target unset when adopting a solution",
                    path,
                ),
            )
        return ()

    issues: list[ValidationIssue] = []
    if not _SEMVER.fullmatch(version):
        issues.append(
            ValidationIssue(
                "invalid-deliverable-version",
                "set deliverable.target_version to a SemVer MAJOR.MINOR.PATCH value",
                path,
            )
        )
    if goal in {"", "null"}:
        issues.append(
            ValidationIssue(
                "missing-deliverable-goal", "name one usable outcome for this version", path
            )
        )

    definition_path = root / "planning/definition.md"
    definition = definition_path.read_text(encoding="utf-8") if definition_path.is_file() else ""
    for heading in ("Smallest version that delivers the value", "Not in the first version"):
        match = re.search(
            rf"^## {re.escape(heading)}\n(.*?)(?=^## |\Z)",
            definition,
            re.MULTILINE | re.DOTALL,
        )
        if not match or not match.group(1).strip() or _UNANSWERED in match.group(1):
            issues.append(
                ValidationIssue(
                    "unbounded-deliverable",
                    f"complete '{heading}' before Build",
                    definition_path,
                )
            )
    return tuple(issues)


def validate_project(root: str | Path) -> tuple[ValidationIssue, ...]:
    """Return structural and secret-safety issues without mutating the project."""

    project_root = Path(root).expanduser().resolve()
    issues: list[ValidationIssue] = []
    if not project_root.is_dir():
        return (
            ValidationIssue("missing-project", "project directory does not exist", project_root),
        )

    manifest_path = project_root / ".agent-builder.json"
    manifest = _load_json(manifest_path, issues) if manifest_path.is_file() else None
    kind = _DEFAULT_KIND
    if isinstance(manifest, dict):
        declared = manifest.get("kind", _DEFAULT_KIND)
        if declared not in _KIND_REQUIRED_FILES:
            issues.append(
                ValidationIssue(
                    "invalid-manifest",
                    f"unknown kind {declared!r}; known kinds: "
                    + ", ".join(sorted(_KIND_REQUIRED_FILES)),
                    manifest_path,
                )
            )
        else:
            kind = declared

    for relative in _REQUIRED_FILES + _KIND_REQUIRED_FILES[kind]:
        if not (project_root / relative).is_file():
            issues.append(
                ValidationIssue("missing-file", "required scaffold file is missing", relative)
            )

    if (
        _uses_solution_gate(manifest)
        and not (project_root / "planning/solution-evaluation.md").is_file()
    ):
        issues.append(
            ValidationIssue(
                "missing-file",
                "required build-or-adopt record is missing",
                Path("planning/solution-evaluation.md"),
            )
        )

    if isinstance(manifest, dict):
        adapters = manifest.get("coding_agent_adapters")
        if (
            not isinstance(adapters, list)
            or not adapters
            or not all(isinstance(adapter, str) for adapter in adapters)
        ):
            issues.append(
                ValidationIssue(
                    "invalid-manifest",
                    "coding_agent_adapters must be a non-empty list of strings",
                    manifest_path,
                )
            )
        else:
            unknown = sorted(set(adapters) - set(_ADAPTER_FILES))
            if unknown:
                issues.append(
                    ValidationIssue(
                        "invalid-manifest",
                        f"unknown coding-agent adapters: {', '.join(unknown)}",
                        manifest_path,
                    )
                )
            for adapter in adapters:
                adapter_path = _ADAPTER_FILES.get(adapter)
                if adapter_path and not (project_root / adapter_path).is_file():
                    issues.append(
                        ValidationIssue(
                            "missing-adapter",
                            f"{adapter} adapter entry point is missing",
                            adapter_path,
                        )
                    )
            if len(adapters) != len(set(adapters)):
                issues.append(
                    ValidationIssue(
                        "invalid-manifest",
                        "coding_agent_adapters must not contain duplicates",
                        manifest_path,
                    )
                )
            for adapter, adapter_path in _ADAPTER_FILES.items():
                if adapter not in adapters and (project_root / adapter_path).exists():
                    issues.append(
                        ValidationIssue(
                            "unexpected-adapter",
                            f"{adapter} entry point exists but is not declared",
                            adapter_path,
                        )
                    )

    state_path = project_root / "governance/project-state.yaml"
    if state_path.is_file():
        state = state_path.read_text(encoding="utf-8")
        declared = _STATUS_LINE.search(state)
        if declared and declared.group(1) not in _PROJECT_STATUSES:
            issues.append(
                ValidationIssue(
                    "invalid-status",
                    f"project status must be one of {', '.join(_PROJECT_STATUSES)}",
                    state_path,
                )
            )
        if not re.search(r"^  current: (?:define|plan|build|review)$", state, re.MULTILINE):
            issues.append(
                ValidationIssue("invalid-phase", "project must have a recognized phase", state_path)
            )

    gitignore_path = project_root / ".gitignore"
    if gitignore_path.is_file():
        gitignore = gitignore_path.read_text(encoding="utf-8")
        for required_pattern in (".env", "*.pem", "*.key", "secrets/"):
            if required_pattern not in gitignore:
                issues.append(
                    ValidationIssue(
                        "unsafe-ignore",
                        f".gitignore does not cover {required_pattern}",
                        gitignore_path,
                    )
                )

    if kind == "agent":
        _validate_contract(project_root, issues)
    _scan_text_files(project_root, issues)
    return tuple(issues)


HERE = Path(__file__).resolve().parent
_CHANGELOG_CANDIDATES = (HERE.parent / "CHANGELOG.md", HERE.parents[2] / "CHANGELOG.md")
_HEADING = re.compile(r"^## \[([^\]]+)\]", re.MULTILINE)


_PHASES = ("define", "plan", "build", "review")
_UNANSWERED = "(not yet answered)"
_DECISION_ID = re.compile(r"^\s*-\s*id:\s*(\S+)", re.MULTILINE)
_DECISION_STATUS = re.compile(r"^\s*status:\s*(\S+)", re.MULTILINE)
_PHASE_CURRENT = re.compile(r"^phase:\n(?:[ \t]+.*\n)*?[ \t]+current:[ \t]*(\S+)", re.MULTILINE)


def proposed_decisions(text: str) -> tuple[str, ...]:
    """Return ids of decisions whose status is still ``proposed``.

    Line-oriented on purpose: the ledger is YAML we wrote ourselves, and the stdlib has no
    YAML parser. Each ``- id:`` line opens a decision; the next ``status:`` line belongs to it.
    """
    proposed: list[str] = []
    entries = list(_DECISION_ID.finditer(text))
    for index, entry in enumerate(entries):
        end = entries[index + 1].start() if index + 1 < len(entries) else len(text)
        status = _DECISION_STATUS.search(text, entry.end(), end)
        if status and status.group(1) == "proposed":
            proposed.append(entry.group(1))
    return tuple(proposed)


def phase_exit_issues(root: str | Path, phase: str) -> tuple[ValidationIssue, ...]:
    """What still blocks this project from leaving ``phase``.

    Two rules apply to every phase (AB-D035): the ledger holds no ``proposed`` decision, and
    the project is actually in the phase being left. Leaving Define additionally requires
    ``planning/definition.md`` with every problem-framing answer filled in (AB-D033).
    """
    project_root = Path(root).expanduser().resolve()
    issues: list[ValidationIssue] = []
    if phase not in _PHASES:
        return (ValidationIssue("unknown-phase", f"phase must be one of {', '.join(_PHASES)}"),)

    state_path = project_root / "governance/project-state.yaml"
    if state_path.is_file():
        match = _PHASE_CURRENT.search(state_path.read_text(encoding="utf-8"))
        current = match.group(1) if match else None
        if current != phase:
            issues.append(
                ValidationIssue(
                    "wrong-phase",
                    f"project-state says phase.current is {current or 'unset'}, not {phase}",
                    state_path,
                )
            )
    else:
        issues.append(ValidationIssue("missing", "governance/project-state.yaml", state_path))

    ledger_path = project_root / "governance/decisions.yaml"
    if ledger_path.is_file():
        for decision_id in proposed_decisions(ledger_path.read_text(encoding="utf-8")):
            issues.append(
                ValidationIssue(
                    "proposed-decision",
                    f"{decision_id} is still proposed; confirm it, reject it, or move it to"
                    " planning/later.md before leaving " + phase,
                    ledger_path,
                )
            )
    else:
        issues.append(ValidationIssue("missing", "governance/decisions.yaml", ledger_path))

    if phase == "define":
        definition_path = project_root / "planning/definition.md"
        if not definition_path.is_file():
            issues.append(
                ValidationIssue(
                    "missing-definition",
                    "planning/definition.md must exist and answer the problem questions",
                    definition_path,
                )
            )
        else:
            text = definition_path.read_text(encoding="utf-8")
            heading = None
            for line in text.splitlines():
                if line.startswith("## "):
                    heading = line[3:].strip()
                elif _UNANSWERED in line and heading:
                    issues.append(
                        ValidationIssue(
                            "unanswered",
                            f"'{heading}' is still {_UNANSWERED}",
                            definition_path,
                        )
                    )
    elif phase == "plan":
        manifest_path = project_root / ".agent-builder.json"
        manifest = _load_json(manifest_path, issues) if manifest_path.is_file() else None
        if _uses_solution_gate(manifest):
            state = state_path.read_text(encoding="utf-8") if state_path.is_file() else ""
            ledger = ledger_path.read_text(encoding="utf-8") if ledger_path.is_file() else ""
            issues.extend(_solution_record_issues(project_root, state, ledger))
            record_path = project_root / "planning/solution-evaluation.md"
            if record_path.is_file():
                fields = dict(_SOLUTION_LINE.findall(record_path.read_text(encoding="utf-8")))
                status = _STATUS_LINE.search(state)
                if fields.get("Outcome", "").strip().lower() == "adopt" and (
                    status and status.group(1) == "archived"
                ):
                    issues.append(
                        ValidationIssue(
                            "adoption-complete",
                            "project is archived in Plan; do not enter Build",
                            state_path,
                        )
                    )
    return tuple(issues)


def changes_since(version: str) -> str:
    """Return the CHANGELOG sections newer than ``version``, or an explanation.

    Deliberately simple: the changelog is the upgrade guide. Agent Builder never rewrites a
    seeded project; this tells a person what they would be opting into.
    """

    changelog = next((path for path in _CHANGELOG_CANDIDATES if path.is_file()), None)
    if changelog is None:
        return (
            "No CHANGELOG.md found beside this skill folder. A copied skill folder does not carry "
            "the changelog; read it in the Agent Builder repository."
        )
    text = changelog.read_text(encoding="utf-8")
    headings = list(_HEADING.finditer(text))
    if not headings:
        return f"{changelog}: no version headings found"
    for index, match in enumerate(headings):
        if match.group(1) == version:
            if index == 0:
                return f"Nothing newer than {version} in {changelog.name}."
            return text[headings[0].start() : match.start()].rstrip() + "\n"
    newest = headings[0].group(1)
    return (
        f"No changelog heading for {version!r}; the newest heading is [{newest}]. "
        f"Showing everything in {changelog.name}:\n\n" + text[headings[0].start() :].rstrip() + "\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="check.py", description=__doc__.splitlines()[0])
    parser.add_argument("target", type=Path, help="root of the generated project")
    parser.add_argument(
        "--since",
        nargs="?",
        const="",
        default=None,
        metavar="VERSION",
        help="print Agent Builder changes since VERSION (default: the project's template_version)",
    )
    parser.add_argument(
        "--leaving",
        choices=_PHASES,
        metavar="PHASE",
        help="check whether the project may leave PHASE (define, plan, build, review)",
    )
    arguments = parser.parse_args(argv)

    if arguments.leaving is not None:
        issues = phase_exit_issues(arguments.target, arguments.leaving)
        if not issues:
            print(f"May leave {arguments.leaving}: nothing unresolved.")
            return 0
        print(f"Cannot leave {arguments.leaving} yet:", file=sys.stderr)
        for issue in issues:
            location = f" ({issue.path})" if issue.path else ""
            print(f"  {issue.code}{location}: {issue.message}", file=sys.stderr)
        return 1

    if arguments.since is not None:
        version = arguments.since
        if not version:
            manifest_path = Path(arguments.target).expanduser().resolve() / ".agent-builder.json"
            try:
                version = json.loads(manifest_path.read_text(encoding="utf-8"))["template_version"]
            except (OSError, ValueError, KeyError) as error:
                print(
                    f"error: cannot read template_version from {manifest_path}: {error}",
                    file=sys.stderr,
                )
                return 2
        print(changes_since(str(version)), end="")
        return 0

    issues = validate_project(arguments.target)
    if not issues:
        print(f"Scaffold valid: {arguments.target.expanduser().resolve()}")
        return 0
    for issue in issues:
        location = f" ({issue.path})" if issue.path else ""
        print(f"{issue.code}{location}: {issue.message}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
