#!/usr/bin/env python3
"""Render every file that states a principle from the single source in ``principles/``.

Stencils live under ``scripts/stencils/`` and mirror the repository layout: the stencil
``scripts/stencils/AGENTS.md`` renders to ``AGENTS.md``. A stencil references a principle as
``{{principle:<id>}}`` (full text), ``{{principle:<id>|short}}`` (the ``## Short form``
section), or ``{{principle:<id>|title}}``. Seed-time placeholders such as ``{{PROJECT_NAME}}``
are left untouched; they are filled later by the scaffolder.

Usage:
    python3 scripts/render.py          # write outputs
    python3 scripts/render.py --check  # exit 1 if any committed output is stale
"""

from __future__ import annotations

import sys

if sys.version_info < (3, 9):  # noqa: UP036 - deliberate guard for older interpreters
    sys.stderr.write(
        f"Agent Builder needs Python 3.9 or newer; this is "
        f"{sys.version_info[0]}.{sys.version_info[1]}. Install a newer Python and run this again.\n"
    )
    sys.exit(2)

import argparse  # noqa: E402
import re  # noqa: E402
from pathlib import Path  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PRINCIPLES_DIR = ROOT / "principles"
STENCILS_DIR = ROOT / "scripts" / "stencils"

TOKEN = re.compile(r"\{\{principle:([a-z0-9-]+)(?:\|(short|title))?\}\}")
FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
SHORT_FORM_HEADING = "\n## Short form\n"
LIST_MARKER = re.compile(r"\s*(?:[-*+]|\d+\.) ")
GENERATED_HEADER = (
    "<!-- Generated by scripts/render.py from scripts/stencils/{stencil} and principles/. "
    "Edit those, not this file. -->\n"
)


class RenderError(RuntimeError):
    """Raised when the sources cannot produce a consistent set of outputs."""


def load_principles(directory: Path = PRINCIPLES_DIR) -> dict[str, dict[str, str]]:
    """Return ``{id: {"title", "full", "short"}}`` for every principle file."""

    principles: dict[str, dict[str, str]] = {}
    for path in sorted(directory.glob("*.md")):
        if path.name == "README.md":
            continue
        text = path.read_text(encoding="utf-8")
        match = FRONT_MATTER.match(text)
        if not match:
            raise RenderError(f"{path}: missing front matter")
        meta = {}
        for line in match.group(1).splitlines():
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
        if "id" not in meta or "title" not in meta:
            raise RenderError(f"{path}: front matter needs id and title")
        body = text[match.end() :]
        full, _, short = body.partition(SHORT_FORM_HEADING)
        if meta["id"] in principles:
            raise RenderError(f"{path}: duplicate principle id {meta['id']}")
        principles[meta["id"]] = {
            "title": meta["title"],
            "full": full.strip("\n"),
            "short": short.strip("\n"),
            "source": path.name,
        }
    if not principles:
        raise RenderError(f"no principles found in {directory}")
    return principles


def stencil_files(directory: Path = STENCILS_DIR) -> list[Path]:
    return sorted(p for p in directory.rglob("*") if p.is_file())


def render_text(stencil: Path, text: str, principles: dict[str, dict[str, str]]) -> str:
    """Fill every principle token in ``text``; raise on unknown ids or missing forms."""

    def replace(match: re.Match[str]) -> str:
        pid, form = match.group(1), match.group(2) or "full"
        if pid not in principles:
            raise RenderError(f"{stencil}: unknown principle id {pid!r}")
        value = principles[pid][form]
        if not value:
            raise RenderError(f"{stencil}: principle {pid!r} has no {form} form")
        # Inside a list item, indent continuation lines so the Markdown stays one item.
        line_start = text.rfind("\n", 0, match.start()) + 1
        prefix = text[line_start : match.start()]
        if LIST_MARKER.fullmatch(prefix):
            value = value.replace("\n", "\n" + " " * len(prefix))
        return value

    rendered = TOKEN.sub(replace, text)
    if "{{principle:" in rendered:
        raise RenderError(f"{stencil}: malformed principle token left after render")
    return rendered


def render_all(principles: dict[str, dict[str, str]], stencils: list[Path]) -> dict[Path, str]:
    """Return ``{output_path: content}`` for every stencil, checking every principle is used."""

    outputs: dict[Path, str] = {}
    used = set()
    for stencil in stencils:
        relative = stencil.relative_to(STENCILS_DIR)
        text = stencil.read_text(encoding="utf-8")
        used.update(m.group(1) for m in TOKEN.finditer(text))
        rendered = render_text(stencil, text, principles)
        if stencil.suffix != ".tmpl":
            header = GENERATED_HEADER.format(stencil=relative.as_posix())
            if rendered.startswith("---\n"):
                # Keep YAML front matter first; hosts parse it from byte zero.
                end = rendered.index("\n---\n", 4) + len("\n---\n")
                rendered = rendered[:end] + header + rendered[end:]
            else:
                rendered = header + rendered
        outputs[ROOT / relative] = rendered
    unused = sorted(set(principles) - used)
    if unused:
        raise RenderError(f"principles never referenced by any stencil: {', '.join(unused)}")
    return outputs


def stale_outputs(outputs: dict[Path, str]) -> list[tuple[Path, str]]:
    """Return ``(path, reason)`` for every output that differs from disk."""

    stale = []
    for path, content in outputs.items():
        if not path.exists():
            stale.append((path, "missing"))
        elif path.read_text(encoding="utf-8") != content:
            stale.append((path, "differs"))
    return stale


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report stale outputs; write nothing")
    args = parser.parse_args(argv)

    try:
        outputs = render_all(load_principles(), stencil_files())
    except RenderError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        stale = stale_outputs(outputs)
        for path, reason in stale:
            print(
                f"{path.relative_to(ROOT)}: {reason} — edit principles/ or scripts/stencils/ "
                "and run scripts/render.py",
                file=sys.stderr,
            )
        return 1 if stale else 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        print(f"rendered {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
